GARMIN_SPORT_TYPE_MAP = {
    1: "running",  # 跑步
    2: "cycling",  # 骑行
    3: "swimming",  # 游泳
    4: "walking",  # 步行
    5: "hiking",  # 徒步
    6: "fitness_equipment",  # 健身器材
    7: "yoga",  # 瑜伽
    8: "strength_training",  # 力量训练
    9: "other",  # 其他
    10: "cardio",  # 有氧
    11: "elliptical",  # 椭圆机
    12: "stairs",  # 爬楼梯
    13: "basketball",  # 篮球
    14: "soccer",  # 足球
    15: "tennis",  # 网球
    16: "golf",  # 高尔夫
    17: "fitness",  # 健身
    18: "dancing",  # 舞蹈
    19: "martial_arts",  # 武术
    20: "skating",  # 滑冰
    21: "skiing",  # 滑雪
    22: "snowboarding",  # 单板滑雪
    23: "water_sports",  # 水上运动
    24: "cycling_sport",  # 竞技骑行
    25: "cycling_touring",  # 旅行骑行
    26: "cycling_mountain",  # 山地骑行
    27: "cycling_road",  # 公路骑行
    28: "cycling_indoor",  # 室内骑行
    29: "running_trail",  # 越野跑
    30: "running_road",  # 公路跑
    31: "running_treadmill",  # 跑步机
    32: "swimming_pool",  # 泳池游泳
    33: "swimming_open_water",  # 公开水域游泳
    34: "walking_fitness",  # 健身步行
    35: "walking_casual",  # 休闲步行
    36: "walking_treadmill",  # 跑步机步行
    37: "hiking_backpacking",  # 背包徒步
    38: "hiking_mountaineering",  # 登山
    39: "elliptical_cross_trainer",  # 椭圆交叉训练
    40: "rowing_machine",  # 划船机
    41: "stair_climber",  # 爬楼机
    42: "strength_circuit",  # 循环力量训练
    43: "strength_free_weights",  # 自由重量训练
    44: "strength_machine",  # 器械力量训练
    45: "yoga_hatha",  # 哈他瑜伽
    46: "yoga_vinyasa",  # 流瑜伽
    47: "yoga_restorative",  # 修复瑜伽
    48: "cardio_aerobic",  # 有氧训练
    49: "cardio_interval",  # 间歇训练
    50: "cardio_kickboxing",  # 跆拳道
    51: "basketball_outdoor",  # 户外篮球
    52: "basketball_indoor",  # 室内篮球
    53: "soccer_outdoor",  # 户外足球
    54: "soccer_indoor",  # 室内足球
    55: "tennis_outdoor",  # 户外网球
    56: "tennis_indoor",  # 室内网球
    57: "golf_course",  # 高尔夫球场
    58: "golf_driving_range",  # 高尔夫练习场
    59: "dancing_ballroom",  # 交谊舞
    60: "dancing_hip_hop",  # 嘻哈舞
    61: "dancing_latin",  # 拉丁舞
    62: "dancing_salsa",  # 萨尔萨舞
    63: "dancing_swing",  # 摇摆舞
    64: "dancing_tango",  # 探戈
    65: "martial_arts_karate",  # 空手道
    66: "martial_arts_taekwondo",  # 跆拳道
    67: "martial_arts_kung_fu",  # 功夫
    68: "martial_arts_judo",  # 柔道
    69: "martial_arts_jujitsu",  # 柔术
    70: "martial_arts_muay_thai",  # 泰拳
    71: "skating_ice",  # 冰上滑冰
    72: "skating_roller",  # 轮滑
    73: "skiing_alpine",  # 高山滑雪
    74: "skiing_cross_country",  # 越野滑雪
    75: "skiing_backcountry",  # 野外滑雪
    76: "snowboarding_freestyle",  # 自由式单板滑雪
    77: "snowboarding_alpine",  # 高山单板滑雪
    78: "water_sports_kayaking",  # 皮划艇
    79: "water_sports_canoeing",  # 独木舟
    80: "water_sports_paddleboarding",  #  paddleboarding
    81: "water_sports_surfing",  # 冲浪
    82: "water_sports_windsurfing",  # 帆板
    83: "water_sports_kitesurfing",  # 风筝冲浪
    84: "water_sports_sailing",  # 帆船
    85: "water_sports_swimming",  # 游泳
    86: "other_sport",  # 其他运动
    87: "other_fitness",  # 其他健身
    88: "other_leisure",  # 其他休闲
    89: "other_work",  # 其他工作
    90: "other_transportation",  # 其他交通
}

GARMIN_URL_DICT = {
    "garmin_connect_activities": "/activitylist-service/activities/search/activities",
    "garmin_connect_fit_download": "/download-service/files/activity",
    "garmin_connect_upload": "/upload-service/upload",
}
